// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTV;

#nullable disable

namespace Ngducanh.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250612163532_Updaten")]
    partial class Updaten
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTV.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 2001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 2001,
                            Name = "Nguyễn Nhật Ánh"
                        },
                        new
                        {
                            AuthorId = 2002,
                            Name = "Hermione Granger"
                        },
                        new
                        {
                            AuthorId = 2003,
                            Name = "Paulo Coelho"
                        },
                        new
                        {
                            AuthorId = 2004,
                            Name = "Stephen Hawking"
                        },
                        new
                        {
                            AuthorId = 2005,
                            Name = "Yuval Noah Harari"
                        },
                        new
                        {
                            AuthorId = 2006,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorId = 2007,
                            Name = "Daniel Kahneman"
                        },
                        new
                        {
                            AuthorId = 2008,
                            Name = "Tony Robbins"
                        },
                        new
                        {
                            AuthorId = 2009,
                            Name = "Malcolm Gladwell"
                        },
                        new
                        {
                            AuthorId = 2010,
                            Name = "George Orwell"
                        },
                        new
                        {
                            AuthorId = 2011,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            AuthorId = 2012,
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            AuthorId = 2013,
                            Name = "Gabriel Garcia Marquez"
                        },
                        new
                        {
                            AuthorId = 2014,
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            AuthorId = 2015,
                            Name = "Sun Tzu"
                        });
                });

            modelBuilder.Entity("QLTV.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 5001L);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 5001,
                            CategoryId = 3007,
                            PublisherId = 4005,
                            StockQuantity = 12,
                            Title = "Dế Mèn Phiêu Lưu Ký"
                        },
                        new
                        {
                            BookId = 5002,
                            CategoryId = 3002,
                            PublisherId = 4002,
                            StockQuantity = 8,
                            Title = "Hoàng Tử Bé"
                        },
                        new
                        {
                            BookId = 5003,
                            CategoryId = 3001,
                            PublisherId = 4004,
                            StockQuantity = 5,
                            Title = "Nhà Giả Kim"
                        },
                        new
                        {
                            BookId = 5004,
                            CategoryId = 3003,
                            PublisherId = 4003,
                            StockQuantity = 3,
                            Title = "Lược Sử Thời Gian"
                        },
                        new
                        {
                            BookId = 5005,
                            CategoryId = 3004,
                            PublisherId = 4003,
                            StockQuantity = 4,
                            Title = "Sapiens: Lược Sử Loài Người"
                        },
                        new
                        {
                            BookId = 5006,
                            CategoryId = 3007,
                            PublisherId = 4005,
                            StockQuantity = 6,
                            Title = "Harry Potter và Hòn Đá Phù Thủy"
                        },
                        new
                        {
                            BookId = 5007,
                            CategoryId = 3006,
                            PublisherId = 4008,
                            StockQuantity = 10,
                            Title = "Tư Duy, Nhanh và Chậm"
                        },
                        new
                        {
                            BookId = 5008,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 2,
                            Title = "Cấu Trúc Dữ Liệu và Giải Thuật"
                        },
                        new
                        {
                            BookId = 5009,
                            CategoryId = 3001,
                            PublisherId = 4002,
                            StockQuantity = 5,
                            Title = "Trên Đường"
                        },
                        new
                        {
                            BookId = 5010,
                            CategoryId = 3006,
                            PublisherId = 4001,
                            StockQuantity = 4,
                            Title = "21 Bài Học Cho Thế Kỷ 21"
                        },
                        new
                        {
                            BookId = 5011,
                            CategoryId = 3002,
                            PublisherId = 4002,
                            StockQuantity = 7,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 5012,
                            CategoryId = 3002,
                            PublisherId = 4002,
                            StockQuantity = 5,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 5013,
                            CategoryId = 3001,
                            PublisherId = 4003,
                            StockQuantity = 6,
                            Title = "Tội Ác và Hình Phạt"
                        },
                        new
                        {
                            BookId = 5014,
                            CategoryId = 3001,
                            PublisherId = 4001,
                            StockQuantity = 4,
                            Title = "Nửa Xuân"
                        },
                        new
                        {
                            BookId = 5015,
                            CategoryId = 3006,
                            PublisherId = 4008,
                            StockQuantity = 9,
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            BookId = 5016,
                            CategoryId = 3006,
                            PublisherId = 4001,
                            StockQuantity = 11,
                            Title = "Đi Tìm Lẽ Sống"
                        },
                        new
                        {
                            BookId = 5017,
                            CategoryId = 3004,
                            PublisherId = 4003,
                            StockQuantity = 3,
                            Title = "Chiến Tranh và Hòa Bình"
                        },
                        new
                        {
                            BookId = 5018,
                            CategoryId = 3008,
                            PublisherId = 4008,
                            StockQuantity = 8,
                            Title = "Bí Quyết Làm Giàu"
                        },
                        new
                        {
                            BookId = 5019,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 2,
                            Title = "Artificial Intelligence Basics"
                        },
                        new
                        {
                            BookId = 5020,
                            CategoryId = 3004,
                            PublisherId = 4002,
                            StockQuantity = 7,
                            Title = "The Art of War"
                        },
                        new
                        {
                            BookId = 5021,
                            CategoryId = 3011,
                            PublisherId = 4004,
                            StockQuantity = 20,
                            Title = "One Piece – Tập 1"
                        },
                        new
                        {
                            BookId = 5022,
                            CategoryId = 3012,
                            PublisherId = 4008,
                            StockQuantity = 15,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            BookId = 5023,
                            CategoryId = 3013,
                            PublisherId = 4002,
                            StockQuantity = 8,
                            Title = "Thơ Trẻ – Cố Quận"
                        },
                        new
                        {
                            BookId = 5024,
                            CategoryId = 3014,
                            PublisherId = 4003,
                            StockQuantity = 10,
                            Title = "Lonely Planet Việt Nam"
                        },
                        new
                        {
                            BookId = 5025,
                            CategoryId = 3015,
                            PublisherId = 4005,
                            StockQuantity = 12,
                            Title = "MasterChef – Công Thức Nấu Ăn"
                        },
                        new
                        {
                            BookId = 5026,
                            CategoryId = 3011,
                            PublisherId = 4005,
                            StockQuantity = 25,
                            Title = "Doraemon – Tập 1"
                        },
                        new
                        {
                            BookId = 5027,
                            CategoryId = 3012,
                            PublisherId = 4001,
                            StockQuantity = 7,
                            Title = "How to Win Friends & Influence People"
                        },
                        new
                        {
                            BookId = 5028,
                            CategoryId = 3013,
                            PublisherId = 4007,
                            StockQuantity = 5,
                            Title = "Thơ Viết Cho Tuổi 20"
                        },
                        new
                        {
                            BookId = 5029,
                            CategoryId = 3014,
                            PublisherId = 4006,
                            StockQuantity = 9,
                            Title = "1001 Địa Điểm Việt Nam"
                        },
                        new
                        {
                            BookId = 5030,
                            CategoryId = 3015,
                            PublisherId = 4006,
                            StockQuantity = 14,
                            Title = "Cẩm Nang Nấu Ăn Gia Đình"
                        });
                });

            modelBuilder.Entity("QLTV.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 5001,
                            AuthorId = 2001
                        },
                        new
                        {
                            BookId = 5002,
                            AuthorId = 2003
                        },
                        new
                        {
                            BookId = 5003,
                            AuthorId = 2003
                        },
                        new
                        {
                            BookId = 5004,
                            AuthorId = 2004
                        },
                        new
                        {
                            BookId = 5005,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5006,
                            AuthorId = 2006
                        },
                        new
                        {
                            BookId = 5007,
                            AuthorId = 2007
                        },
                        new
                        {
                            BookId = 5008,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5009,
                            AuthorId = 2001
                        },
                        new
                        {
                            BookId = 5010,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5011,
                            AuthorId = 2010
                        },
                        new
                        {
                            BookId = 5012,
                            AuthorId = 2011
                        },
                        new
                        {
                            BookId = 5013,
                            AuthorId = 2012
                        },
                        new
                        {
                            BookId = 5014,
                            AuthorId = 2001
                        },
                        new
                        {
                            BookId = 5015,
                            AuthorId = 2008
                        },
                        new
                        {
                            BookId = 5016,
                            AuthorId = 2002
                        },
                        new
                        {
                            BookId = 5017,
                            AuthorId = 2009
                        },
                        new
                        {
                            BookId = 5018,
                            AuthorId = 2008
                        },
                        new
                        {
                            BookId = 5019,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5020,
                            AuthorId = 2015
                        },
                        new
                        {
                            BookId = 5003,
                            AuthorId = 2011
                        },
                        new
                        {
                            BookId = 5007,
                            AuthorId = 2009
                        },
                        new
                        {
                            BookId = 5010,
                            AuthorId = 2002
                        },
                        new
                        {
                            BookId = 5016,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5018,
                            AuthorId = 2002
                        });
                });

            modelBuilder.Entity("QLTV.Models.BorrowDetail", b =>
                {
                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowDetails");

                    b.HasData(
                        new
                        {
                            ReceiptId = 6001,
                            BookId = 5001,
                            ActualReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6001,
                            BookId = 5002,
                            ActualReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6002,
                            BookId = 5003,
                            ActualReturnDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6002,
                            BookId = 5004,
                            ActualReturnDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6003,
                            BookId = 5005
                        },
                        new
                        {
                            ReceiptId = 6003,
                            BookId = 5006
                        },
                        new
                        {
                            ReceiptId = 6004,
                            BookId = 5007
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BookId = 5008,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 15000m
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BookId = 5009,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 20000m
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BookId = 5010,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 2.00m
                        },
                        new
                        {
                            ReceiptId = 6006,
                            BookId = 5011
                        },
                        new
                        {
                            ReceiptId = 6006,
                            BookId = 5012
                        },
                        new
                        {
                            ReceiptId = 6007,
                            BookId = 5013
                        },
                        new
                        {
                            ReceiptId = 6007,
                            BookId = 5014
                        },
                        new
                        {
                            ReceiptId = 6008,
                            BookId = 5015,
                            ActualReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6008,
                            BookId = 5016,
                            ActualReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6009,
                            BookId = 5017
                        },
                        new
                        {
                            ReceiptId = 6009,
                            BookId = 5018
                        },
                        new
                        {
                            ReceiptId = 6010,
                            BookId = 5019
                        },
                        new
                        {
                            ReceiptId = 6010,
                            BookId = 5020
                        });
                });

            modelBuilder.Entity("QLTV.Models.BorrowReceipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"), 6001L);

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowReceipts");

                    b.HasData(
                        new
                        {
                            ReceiptId = 6001,
                            BorrowDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1001
                        },
                        new
                        {
                            ReceiptId = 6002,
                            BorrowDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1002
                        },
                        new
                        {
                            ReceiptId = 6003,
                            BorrowDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1003
                        },
                        new
                        {
                            ReceiptId = 6004,
                            BorrowDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1001
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BorrowDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1002
                        },
                        new
                        {
                            ReceiptId = 6006,
                            BorrowDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1003
                        },
                        new
                        {
                            ReceiptId = 6007,
                            BorrowDate = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1001
                        },
                        new
                        {
                            ReceiptId = 6008,
                            BorrowDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1002
                        },
                        new
                        {
                            ReceiptId = 6009,
                            BorrowDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1003
                        },
                        new
                        {
                            ReceiptId = 6010,
                            BorrowDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1001
                        });
                });

            modelBuilder.Entity("QLTV.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 3001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 3001,
                            Name = "Văn học Việt Nam"
                        },
                        new
                        {
                            CategoryId = 3002,
                            Name = "Văn học nước ngoài"
                        },
                        new
                        {
                            CategoryId = 3003,
                            Name = "Nghiên cứu khoa học"
                        },
                        new
                        {
                            CategoryId = 3004,
                            Name = "Lịch sử – Địa lý"
                        },
                        new
                        {
                            CategoryId = 3005,
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            CategoryId = 3006,
                            Name = "Tâm lý – Kỹ năng sống"
                        },
                        new
                        {
                            CategoryId = 3007,
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            CategoryId = 3008,
                            Name = "Kinh tế – Quản trị"
                        },
                        new
                        {
                            CategoryId = 3009,
                            Name = "Y học – Sức khỏe"
                        },
                        new
                        {
                            CategoryId = 3010,
                            Name = "Nghệ thuật – Kiến trúc"
                        },
                        new
                        {
                            CategoryId = 3011,
                            Name = "Truyện tranh – Manga"
                        },
                        new
                        {
                            CategoryId = 3012,
                            Name = "Tự lực – Phát triển bản thân"
                        },
                        new
                        {
                            CategoryId = 3013,
                            Name = "Thơ ca"
                        },
                        new
                        {
                            CategoryId = 3014,
                            Name = "Du lịch – Khám phá"
                        },
                        new
                        {
                            CategoryId = 3015,
                            Name = "Ẩm thực – Nấu ăn"
                        });
                });

            modelBuilder.Entity("QLTV.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"), 4001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherId = 4001,
                            Name = "NXB Giáo dục Việt Nam"
                        },
                        new
                        {
                            PublisherId = 4002,
                            Name = "NXB Văn hóa – Thông tin"
                        },
                        new
                        {
                            PublisherId = 4003,
                            Name = "NXB Khoa học và Kỹ thuật"
                        },
                        new
                        {
                            PublisherId = 4004,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            PublisherId = 4005,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            PublisherId = 4006,
                            Name = "NXB Thống Kê"
                        },
                        new
                        {
                            PublisherId = 4007,
                            Name = "NXB Đại học Quốc gia"
                        },
                        new
                        {
                            PublisherId = 4008,
                            Name = "NXB Công nghệ Thông tin"
                        });
                });

            modelBuilder.Entity("QLTV.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1001L);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1001,
                            Address = "Số 12, ngõ 34 Phố Hoàng Hoa Thám, Quận Ba Đình, Hà Nội",
                            Email = "vanvu@gmail.com",
                            FullName = "Nguyễn Văn Vũ",
                            Password = "P@ssw0rd1",
                            Phone = "0912345678",
                            Username = "nguyenvanvu"
                        },
                        new
                        {
                            UserId = 1002,
                            Address = "Số 45, Đường 3/2, Phường Hưng Lợi, Quận Ninh Kiều, TP. Cần Thơ",
                            Email = "thiba@gmail.com",
                            FullName = "Trần Thị Ba",
                            Password = "B@Password2",
                            Phone = "0987654321",
                            Username = "tranthiba"
                        },
                        new
                        {
                            UserId = 1003,
                            Address = "Số 78, Phố Nguyễn Văn Cừ, Phường Gia Thuỷ, TP. Bắc Ninh",
                            Email = "vanchi@gmail.com",
                            FullName = "Lê Văn Chi",
                            Password = "Ch1Secure!",
                            Phone = "0901234567",
                            Username = "levanchi"
                        });
                });

            modelBuilder.Entity("QLTV.Models.Book", b =>
                {
                    b.HasOne("QLTV.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTV.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("QLTV.Models.BookAuthor", b =>
                {
                    b.HasOne("QLTV.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTV.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLTV.Models.BorrowDetail", b =>
                {
                    b.HasOne("QLTV.Models.Book", "Book")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTV.Models.BorrowReceipt", "BorrowReceipt")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowReceipt");
                });

            modelBuilder.Entity("QLTV.Models.BorrowReceipt", b =>
                {
                    b.HasOne("QLTV.Models.User", "User")
                        .WithMany("BorrowReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLTV.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("QLTV.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("QLTV.Models.BorrowReceipt", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("QLTV.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLTV.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLTV.Models.User", b =>
                {
                    b.Navigation("BorrowReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
