// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLTV;

#nullable disable

namespace Ngducanh.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250614053753_Users")]
    partial class Users
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLTV.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"), 2001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 2001,
                            Name = "Nguyễn Nhật Ánh"
                        },
                        new
                        {
                            AuthorId = 2002,
                            Name = "Hermione Granger"
                        },
                        new
                        {
                            AuthorId = 2003,
                            Name = "Paulo Coelho"
                        },
                        new
                        {
                            AuthorId = 2004,
                            Name = "Stephen Hawking"
                        },
                        new
                        {
                            AuthorId = 2005,
                            Name = "Yuval Noah Harari"
                        },
                        new
                        {
                            AuthorId = 2006,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorId = 2007,
                            Name = "Daniel Kahneman"
                        },
                        new
                        {
                            AuthorId = 2008,
                            Name = "Tony Robbins"
                        },
                        new
                        {
                            AuthorId = 2009,
                            Name = "Malcolm Gladwell"
                        },
                        new
                        {
                            AuthorId = 2010,
                            Name = "George Orwell"
                        },
                        new
                        {
                            AuthorId = 2011,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            AuthorId = 2012,
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            AuthorId = 2013,
                            Name = "Gabriel Garcia Marquez"
                        },
                        new
                        {
                            AuthorId = 2014,
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            AuthorId = 2015,
                            Name = "Sun Tzu"
                        },
                        new
                        {
                            AuthorId = 2016,
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            AuthorId = 2017,
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            AuthorId = 2018,
                            Name = "Edgar Allan Poe"
                        },
                        new
                        {
                            AuthorId = 2019,
                            Name = "Ralph Waldo Emerson"
                        },
                        new
                        {
                            AuthorId = 2020,
                            Name = "Đỗ Phấn"
                        },
                        new
                        {
                            AuthorId = 2021,
                            Name = "Arthur C. Clarke"
                        },
                        new
                        {
                            AuthorId = 2022,
                            Name = "Nicholas Sparks"
                        },
                        new
                        {
                            AuthorId = 2023,
                            Name = "Dale Carnegie"
                        },
                        new
                        {
                            AuthorId = 2024,
                            Name = "Robert Kiyosaki"
                        },
                        new
                        {
                            AuthorId = 2025,
                            Name = "Stephen R. Covey"
                        },
                        new
                        {
                            AuthorId = 2026,
                            Name = "Nguyễn Trãi"
                        },
                        new
                        {
                            AuthorId = 2027,
                            Name = "William Shakespeare"
                        },
                        new
                        {
                            AuthorId = 2028,
                            Name = "Sigmund Freud"
                        },
                        new
                        {
                            AuthorId = 2029,
                            Name = "Noam Chomsky"
                        },
                        new
                        {
                            AuthorId = 2030,
                            Name = "Trần Đại Nghĩa"
                        });
                });

            modelBuilder.Entity("QLTV.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"), 5001L);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublisherId")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 5001,
                            CategoryId = 3007,
                            PublisherId = 4005,
                            StockQuantity = 12,
                            Title = "Dế Mèn Phiêu Lưu Ký"
                        },
                        new
                        {
                            BookId = 5002,
                            CategoryId = 3002,
                            PublisherId = 4002,
                            StockQuantity = 8,
                            Title = "Hoàng Tử Bé"
                        },
                        new
                        {
                            BookId = 5003,
                            CategoryId = 3001,
                            PublisherId = 4004,
                            StockQuantity = 5,
                            Title = "Nhà Giả Kim"
                        },
                        new
                        {
                            BookId = 5004,
                            CategoryId = 3003,
                            PublisherId = 4003,
                            StockQuantity = 3,
                            Title = "Lược Sử Thời Gian"
                        },
                        new
                        {
                            BookId = 5005,
                            CategoryId = 3004,
                            PublisherId = 4003,
                            StockQuantity = 4,
                            Title = "Sapiens: Lược Sử Loài Người"
                        },
                        new
                        {
                            BookId = 5006,
                            CategoryId = 3007,
                            PublisherId = 4005,
                            StockQuantity = 6,
                            Title = "Harry Potter và Hòn Đá Phù Thủy"
                        },
                        new
                        {
                            BookId = 5007,
                            CategoryId = 3006,
                            PublisherId = 4008,
                            StockQuantity = 10,
                            Title = "Tư Duy, Nhanh và Chậm"
                        },
                        new
                        {
                            BookId = 5008,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 2,
                            Title = "Cấu Trúc Dữ Liệu và Giải Thuật"
                        },
                        new
                        {
                            BookId = 5009,
                            CategoryId = 3001,
                            PublisherId = 4002,
                            StockQuantity = 5,
                            Title = "Trên Đường"
                        },
                        new
                        {
                            BookId = 5010,
                            CategoryId = 3006,
                            PublisherId = 4001,
                            StockQuantity = 4,
                            Title = "21 Bài Học Cho Thế Kỷ 21"
                        },
                        new
                        {
                            BookId = 5011,
                            CategoryId = 3002,
                            PublisherId = 4002,
                            StockQuantity = 7,
                            Title = "1984"
                        },
                        new
                        {
                            BookId = 5012,
                            CategoryId = 3002,
                            PublisherId = 4002,
                            StockQuantity = 5,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            BookId = 5013,
                            CategoryId = 3001,
                            PublisherId = 4003,
                            StockQuantity = 6,
                            Title = "Tội Ác và Hình Phạt"
                        },
                        new
                        {
                            BookId = 5014,
                            CategoryId = 3001,
                            PublisherId = 4001,
                            StockQuantity = 4,
                            Title = "Nửa Xuân"
                        },
                        new
                        {
                            BookId = 5015,
                            CategoryId = 3006,
                            PublisherId = 4008,
                            StockQuantity = 9,
                            Title = "The Power of Habit"
                        },
                        new
                        {
                            BookId = 5016,
                            CategoryId = 3006,
                            PublisherId = 4001,
                            StockQuantity = 11,
                            Title = "Đi Tìm Lẽ Sống"
                        },
                        new
                        {
                            BookId = 5017,
                            CategoryId = 3004,
                            PublisherId = 4003,
                            StockQuantity = 3,
                            Title = "Chiến Tranh và Hòa Bình"
                        },
                        new
                        {
                            BookId = 5018,
                            CategoryId = 3008,
                            PublisherId = 4008,
                            StockQuantity = 8,
                            Title = "Bí Quyết Làm Giàu"
                        },
                        new
                        {
                            BookId = 5019,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 2,
                            Title = "Artificial Intelligence Basics"
                        },
                        new
                        {
                            BookId = 5020,
                            CategoryId = 3004,
                            PublisherId = 4002,
                            StockQuantity = 7,
                            Title = "The Art of War"
                        },
                        new
                        {
                            BookId = 5021,
                            CategoryId = 3011,
                            PublisherId = 4004,
                            StockQuantity = 20,
                            Title = "One Piece – Tập 1"
                        },
                        new
                        {
                            BookId = 5022,
                            CategoryId = 3012,
                            PublisherId = 4008,
                            StockQuantity = 15,
                            Title = "Atomic Habits"
                        },
                        new
                        {
                            BookId = 5023,
                            CategoryId = 3013,
                            PublisherId = 4002,
                            StockQuantity = 8,
                            Title = "Thơ Trẻ – Cố Quận"
                        },
                        new
                        {
                            BookId = 5024,
                            CategoryId = 3014,
                            PublisherId = 4003,
                            StockQuantity = 10,
                            Title = "Lonely Planet Việt Nam"
                        },
                        new
                        {
                            BookId = 5025,
                            CategoryId = 3015,
                            PublisherId = 4005,
                            StockQuantity = 12,
                            Title = "MasterChef – Công Thức Nấu Ăn"
                        },
                        new
                        {
                            BookId = 5026,
                            CategoryId = 3011,
                            PublisherId = 4005,
                            StockQuantity = 25,
                            Title = "Doraemon – Tập 1"
                        },
                        new
                        {
                            BookId = 5027,
                            CategoryId = 3012,
                            PublisherId = 4001,
                            StockQuantity = 7,
                            Title = "How to Win Friends & Influence People"
                        },
                        new
                        {
                            BookId = 5028,
                            CategoryId = 3013,
                            PublisherId = 4007,
                            StockQuantity = 5,
                            Title = "Thơ Viết Cho Tuổi 20"
                        },
                        new
                        {
                            BookId = 5029,
                            CategoryId = 3014,
                            PublisherId = 4006,
                            StockQuantity = 9,
                            Title = "1001 Địa Điểm Việt Nam"
                        },
                        new
                        {
                            BookId = 5030,
                            CategoryId = 3015,
                            PublisherId = 4006,
                            StockQuantity = 14,
                            Title = "Cẩm Nang Nấu Ăn Gia Đình"
                        },
                        new
                        {
                            BookId = 5031,
                            CategoryId = 3017,
                            PublisherId = 4009,
                            StockQuantity = 7,
                            Title = "Ông già và biển cả"
                        },
                        new
                        {
                            BookId = 5032,
                            CategoryId = 3017,
                            PublisherId = 4010,
                            StockQuantity = 5,
                            Title = "Án mạng trên chuyến tàu tốc hành phương Đông"
                        },
                        new
                        {
                            BookId = 5033,
                            CategoryId = 3018,
                            PublisherId = 4011,
                            StockQuantity = 4,
                            Title = "Con quạ và các truyện khác"
                        },
                        new
                        {
                            BookId = 5034,
                            CategoryId = 3016,
                            PublisherId = 4009,
                            StockQuantity = 6,
                            Title = "Tản văn Du ký"
                        },
                        new
                        {
                            BookId = 5035,
                            CategoryId = 3020,
                            PublisherId = 4011,
                            StockQuantity = 3,
                            Title = "Tinh thần triết học"
                        },
                        new
                        {
                            BookId = 5036,
                            CategoryId = 3021,
                            PublisherId = 4012,
                            StockQuantity = 5,
                            Title = "2001: A Space Odyssey"
                        },
                        new
                        {
                            BookId = 5037,
                            CategoryId = 3022,
                            PublisherId = 4013,
                            StockQuantity = 8,
                            Title = "Notebook – Nhật ký tình yêu"
                        },
                        new
                        {
                            BookId = 5038,
                            CategoryId = 3023,
                            PublisherId = 4012,
                            StockQuantity = 10,
                            Title = "How to Win Friends"
                        },
                        new
                        {
                            BookId = 5039,
                            CategoryId = 3024,
                            PublisherId = 4014,
                            StockQuantity = 7,
                            Title = "Rich Dad Poor Dad"
                        },
                        new
                        {
                            BookId = 5040,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 6,
                            Title = "7 Thói Quen Hiệu Quả"
                        },
                        new
                        {
                            BookId = 5041,
                            CategoryId = 3026,
                            PublisherId = 4015,
                            StockQuantity = 5,
                            Title = "Lược sử phát minh"
                        },
                        new
                        {
                            BookId = 5042,
                            CategoryId = 3027,
                            PublisherId = 4016,
                            StockQuantity = 7,
                            Title = "Harry Potter và Phòng Chứa Bí Ẩn"
                        },
                        new
                        {
                            BookId = 5043,
                            CategoryId = 3028,
                            PublisherId = 4015,
                            StockQuantity = 3,
                            Title = "Luật Dân sự Việt Nam"
                        },
                        new
                        {
                            BookId = 5044,
                            CategoryId = 3029,
                            PublisherId = 4015,
                            StockQuantity = 4,
                            Title = "Toán Cao Cấp – Đại cương"
                        },
                        new
                        {
                            BookId = 5045,
                            CategoryId = 3030,
                            PublisherId = 4016,
                            StockQuantity = 6,
                            Title = "Y học cổ truyền Việt Nam"
                        },
                        new
                        {
                            BookId = 5046,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 15,
                            Title = "Lập Trình C# Toàn Tập"
                        },
                        new
                        {
                            BookId = 5047,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 8,
                            Title = "Thiết Kế Kiến Trúc Phần Mềm"
                        },
                        new
                        {
                            BookId = 5048,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 12,
                            Title = "Giải Thuật và Cấu Trúc Dữ Liệu"
                        },
                        new
                        {
                            BookId = 5049,
                            CategoryId = 3005,
                            PublisherId = 4014,
                            StockQuantity = 10,
                            Title = "An Ninh Mạng Cơ Bản"
                        },
                        new
                        {
                            BookId = 5050,
                            CategoryId = 3005,
                            PublisherId = 4012,
                            StockQuantity = 7,
                            Title = "Hướng Dẫn ReactJS"
                        },
                        new
                        {
                            BookId = 5051,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 9,
                            Title = "Kỹ Năng Giao Tiếp Trong Công Việc"
                        },
                        new
                        {
                            BookId = 5052,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 6,
                            Title = "Nghệ Thuật Thuyết Phục"
                        },
                        new
                        {
                            BookId = 5053,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 5,
                            Title = "Quản Trị Mạng CCNA"
                        },
                        new
                        {
                            BookId = 5054,
                            CategoryId = 3005,
                            PublisherId = 4009,
                            StockQuantity = 11,
                            Title = "Phân Tích Dữ Liệu với Python"
                        },
                        new
                        {
                            BookId = 5055,
                            CategoryId = 3005,
                            PublisherId = 4014,
                            StockQuantity = 4,
                            Title = "Machine Learning Cơ Bản"
                        },
                        new
                        {
                            BookId = 5056,
                            CategoryId = 3005,
                            PublisherId = 4014,
                            StockQuantity = 5,
                            Title = "Deep Learning Cơ Bản"
                        },
                        new
                        {
                            BookId = 5057,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 8,
                            Title = "Kỹ Năng Lãnh Đạo"
                        },
                        new
                        {
                            BookId = 5058,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 7,
                            Title = "Phát Triển Ứng Dụng Android"
                        },
                        new
                        {
                            BookId = 5059,
                            CategoryId = 3005,
                            PublisherId = 4009,
                            StockQuantity = 10,
                            Title = "C# Trong Thực Tiễn"
                        },
                        new
                        {
                            BookId = 5060,
                            CategoryId = 3005,
                            PublisherId = 4012,
                            StockQuantity = 6,
                            Title = "Docker và Kubernetes"
                        },
                        new
                        {
                            BookId = 5061,
                            CategoryId = 3006,
                            PublisherId = 4011,
                            StockQuantity = 9,
                            Title = "Phân Tích Hành Vi Người Dùng"
                        },
                        new
                        {
                            BookId = 5062,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 4,
                            Title = "Quản Trị Dự Án Agile"
                        },
                        new
                        {
                            BookId = 5063,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 5,
                            Title = "Kiến Trúc Microservices"
                        },
                        new
                        {
                            BookId = 5064,
                            CategoryId = 3023,
                            PublisherId = 4009,
                            StockQuantity = 7,
                            Title = "Trò Chuyện Với Stanley"
                        },
                        new
                        {
                            BookId = 5065,
                            CategoryId = 3014,
                            PublisherId = 4015,
                            StockQuantity = 3,
                            Title = "Hành Trình Về Phương Đông"
                        },
                        new
                        {
                            BookId = 5066,
                            CategoryId = 3005,
                            PublisherId = 4012,
                            StockQuantity = 8,
                            Title = "Thiết Kế UX/UI Cơ Bản"
                        },
                        new
                        {
                            BookId = 5067,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 6,
                            Title = "Phương Pháp Đặt Câu Hỏi"
                        },
                        new
                        {
                            BookId = 5068,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 12,
                            Title = "Lập Trình Python"
                        },
                        new
                        {
                            BookId = 5069,
                            CategoryId = 3009,
                            PublisherId = 4006,
                            StockQuantity = 5,
                            Title = "An Toàn Thực Phẩm"
                        },
                        new
                        {
                            BookId = 5070,
                            CategoryId = 3014,
                            PublisherId = 4002,
                            StockQuantity = 7,
                            Title = "Kỹ Thuật Chụp Ảnh"
                        },
                        new
                        {
                            BookId = 5071,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 4,
                            Title = "Quản Lý Nhân Sự Hiện Đại"
                        },
                        new
                        {
                            BookId = 5072,
                            CategoryId = 3012,
                            PublisherId = 4014,
                            StockQuantity = 9,
                            Title = "Sức Mạnh Thói Quen"
                        },
                        new
                        {
                            BookId = 5073,
                            CategoryId = 3020,
                            PublisherId = 4003,
                            StockQuantity = 3,
                            Title = "Ngôn Ngữ Cơ Thể"
                        },
                        new
                        {
                            BookId = 5074,
                            CategoryId = 3003,
                            PublisherId = 4001,
                            StockQuantity = 6,
                            Title = "Khoa Học Hành Vi"
                        },
                        new
                        {
                            BookId = 5075,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 8,
                            Title = "Thuyết Trình Tuyệt Đỉnh"
                        },
                        new
                        {
                            BookId = 5076,
                            CategoryId = 3005,
                            PublisherId = 4014,
                            StockQuantity = 5,
                            Title = "Công Nghệ Blockchain"
                        },
                        new
                        {
                            BookId = 5077,
                            CategoryId = 3028,
                            PublisherId = 4015,
                            StockQuantity = 4,
                            Title = "Luật Hình Sự Cơ Bản"
                        },
                        new
                        {
                            BookId = 5078,
                            CategoryId = 3016,
                            PublisherId = 4009,
                            StockQuantity = 7,
                            Title = "Viết Kịch Bản Phim"
                        },
                        new
                        {
                            BookId = 5079,
                            CategoryId = 3010,
                            PublisherId = 4002,
                            StockQuantity = 5,
                            Title = "Âm Nhạc Thế Kỷ 21"
                        },
                        new
                        {
                            BookId = 5080,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 6,
                            Title = "Khởi Nghiệp Tinh Gọn"
                        },
                        new
                        {
                            BookId = 5081,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 9,
                            Title = "Xử Lý Ngôn Ngữ Tự Nhiên"
                        },
                        new
                        {
                            BookId = 5082,
                            CategoryId = 3006,
                            PublisherId = 4001,
                            StockQuantity = 10,
                            Title = "Psychology of Money"
                        },
                        new
                        {
                            BookId = 5083,
                            CategoryId = 3024,
                            PublisherId = 4012,
                            StockQuantity = 5,
                            Title = "Nghiên Cứu Thị Trường"
                        },
                        new
                        {
                            BookId = 5084,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 7,
                            Title = "Châm Ngôn Thành Công"
                        },
                        new
                        {
                            BookId = 5085,
                            CategoryId = 3006,
                            PublisherId = 4006,
                            StockQuantity = 4,
                            Title = "Sách Về Thiền Định"
                        },
                        new
                        {
                            BookId = 5086,
                            CategoryId = 3010,
                            PublisherId = 4002,
                            StockQuantity = 6,
                            Title = "Lý Thuyết Âm Nhạc"
                        },
                        new
                        {
                            BookId = 5087,
                            CategoryId = 3009,
                            PublisherId = 4006,
                            StockQuantity = 5,
                            Title = "Dinh Dưỡng Học"
                        },
                        new
                        {
                            BookId = 5088,
                            CategoryId = 3029,
                            PublisherId = 4015,
                            StockQuantity = 3,
                            Title = "Thủy Văn Cơ Sở"
                        },
                        new
                        {
                            BookId = 5089,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 12,
                            Title = "Lập Trình Web Toàn Tập"
                        },
                        new
                        {
                            BookId = 5090,
                            CategoryId = 3005,
                            PublisherId = 4014,
                            StockQuantity = 8,
                            Title = "Công Nghệ IoT"
                        },
                        new
                        {
                            BookId = 5091,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 5,
                            Title = "Quản Trị Rủi Ro"
                        },
                        new
                        {
                            BookId = 5092,
                            CategoryId = 3013,
                            PublisherId = 4002,
                            StockQuantity = 7,
                            Title = "Thơ Tình Việt Nam"
                        },
                        new
                        {
                            BookId = 5093,
                            CategoryId = 3014,
                            PublisherId = 4015,
                            StockQuantity = 6,
                            Title = "Du Lịch Tây Bắc"
                        },
                        new
                        {
                            BookId = 5094,
                            CategoryId = 3005,
                            PublisherId = 4009,
                            StockQuantity = 4,
                            Title = "Quản Lý Dữ Liệu Lớn"
                        },
                        new
                        {
                            BookId = 5095,
                            CategoryId = 3029,
                            PublisherId = 4015,
                            StockQuantity = 5,
                            Title = "Toán Rời Rạc"
                        },
                        new
                        {
                            BookId = 5096,
                            CategoryId = 3005,
                            PublisherId = 4014,
                            StockQuantity = 3,
                            Title = "Blockchain trong Ngân Hàng"
                        },
                        new
                        {
                            BookId = 5097,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 7,
                            Title = "Xử Lý Ảnh Số"
                        },
                        new
                        {
                            BookId = 5098,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 5,
                            Title = "Phân Tích Tài Chính"
                        },
                        new
                        {
                            BookId = 5099,
                            CategoryId = 3025,
                            PublisherId = 4013,
                            StockQuantity = 8,
                            Title = "Hạt Giống Tâm Hồn"
                        },
                        new
                        {
                            BookId = 5100,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 6,
                            Title = "Sách Về Chiến Lược"
                        },
                        new
                        {
                            BookId = 5101,
                            CategoryId = 3005,
                            PublisherId = 4008,
                            StockQuantity = 9,
                            Title = "Thiết Kế Game"
                        },
                        new
                        {
                            BookId = 5102,
                            CategoryId = 3024,
                            PublisherId = 4010,
                            StockQuantity = 4,
                            Title = "Quản Trị Công Nghệ"
                        },
                        new
                        {
                            BookId = 5103,
                            CategoryId = 3005,
                            PublisherId = 4009,
                            StockQuantity = 7,
                            Title = "Phát Triển iOS"
                        },
                        new
                        {
                            BookId = 5104,
                            CategoryId = 3013,
                            PublisherId = 4002,
                            StockQuantity = 5,
                            Title = "Thơ Trẻ"
                        },
                        new
                        {
                            BookId = 5105,
                            CategoryId = 3015,
                            PublisherId = 4005,
                            StockQuantity = 10,
                            Title = "Ẩm Thực Việt"
                        });
                });

            modelBuilder.Entity("QLTV.Models.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BookAuthors");

                    b.HasData(
                        new
                        {
                            BookId = 5001,
                            AuthorId = 2001
                        },
                        new
                        {
                            BookId = 5002,
                            AuthorId = 2003
                        },
                        new
                        {
                            BookId = 5003,
                            AuthorId = 2003
                        },
                        new
                        {
                            BookId = 5004,
                            AuthorId = 2004
                        },
                        new
                        {
                            BookId = 5005,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5006,
                            AuthorId = 2006
                        },
                        new
                        {
                            BookId = 5007,
                            AuthorId = 2007
                        },
                        new
                        {
                            BookId = 5008,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5009,
                            AuthorId = 2001
                        },
                        new
                        {
                            BookId = 5010,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5011,
                            AuthorId = 2010
                        },
                        new
                        {
                            BookId = 5012,
                            AuthorId = 2011
                        },
                        new
                        {
                            BookId = 5013,
                            AuthorId = 2012
                        },
                        new
                        {
                            BookId = 5014,
                            AuthorId = 2001
                        },
                        new
                        {
                            BookId = 5015,
                            AuthorId = 2008
                        },
                        new
                        {
                            BookId = 5016,
                            AuthorId = 2002
                        },
                        new
                        {
                            BookId = 5017,
                            AuthorId = 2009
                        },
                        new
                        {
                            BookId = 5018,
                            AuthorId = 2008
                        },
                        new
                        {
                            BookId = 5019,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5020,
                            AuthorId = 2015
                        },
                        new
                        {
                            BookId = 5003,
                            AuthorId = 2011
                        },
                        new
                        {
                            BookId = 5007,
                            AuthorId = 2009
                        },
                        new
                        {
                            BookId = 5010,
                            AuthorId = 2002
                        },
                        new
                        {
                            BookId = 5016,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5018,
                            AuthorId = 2002
                        },
                        new
                        {
                            BookId = 5031,
                            AuthorId = 2016
                        },
                        new
                        {
                            BookId = 5032,
                            AuthorId = 2017
                        },
                        new
                        {
                            BookId = 5033,
                            AuthorId = 2018
                        },
                        new
                        {
                            BookId = 5034,
                            AuthorId = 2019
                        },
                        new
                        {
                            BookId = 5035,
                            AuthorId = 2020
                        },
                        new
                        {
                            BookId = 5036,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5037,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5038,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5039,
                            AuthorId = 2024
                        },
                        new
                        {
                            BookId = 5040,
                            AuthorId = 2025
                        },
                        new
                        {
                            BookId = 5041,
                            AuthorId = 2026
                        },
                        new
                        {
                            BookId = 5042,
                            AuthorId = 2026
                        },
                        new
                        {
                            BookId = 5043,
                            AuthorId = 2027
                        },
                        new
                        {
                            BookId = 5044,
                            AuthorId = 2028
                        },
                        new
                        {
                            BookId = 5045,
                            AuthorId = 2029
                        },
                        new
                        {
                            BookId = 5046,
                            AuthorId = 2028
                        },
                        new
                        {
                            BookId = 5047,
                            AuthorId = 2029
                        },
                        new
                        {
                            BookId = 5048,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5049,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5050,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5051,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5052,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5053,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5054,
                            AuthorId = 2017
                        },
                        new
                        {
                            BookId = 5055,
                            AuthorId = 2024
                        },
                        new
                        {
                            BookId = 5056,
                            AuthorId = 2024
                        },
                        new
                        {
                            BookId = 5057,
                            AuthorId = 2025
                        },
                        new
                        {
                            BookId = 5058,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5059,
                            AuthorId = 2016
                        },
                        new
                        {
                            BookId = 5060,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5061,
                            AuthorId = 2027
                        },
                        new
                        {
                            BookId = 5062,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5063,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5064,
                            AuthorId = 2029
                        },
                        new
                        {
                            BookId = 5065,
                            AuthorId = 2026
                        },
                        new
                        {
                            BookId = 5066,
                            AuthorId = 2024
                        },
                        new
                        {
                            BookId = 5067,
                            AuthorId = 2025
                        },
                        new
                        {
                            BookId = 5068,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5069,
                            AuthorId = 2027
                        },
                        new
                        {
                            BookId = 5070,
                            AuthorId = 2029
                        },
                        new
                        {
                            BookId = 5071,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5072,
                            AuthorId = 2025
                        },
                        new
                        {
                            BookId = 5073,
                            AuthorId = 2029
                        },
                        new
                        {
                            BookId = 5074,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5075,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5076,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5077,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5078,
                            AuthorId = 2016
                        },
                        new
                        {
                            BookId = 5079,
                            AuthorId = 2010
                        },
                        new
                        {
                            BookId = 5080,
                            AuthorId = 2017
                        },
                        new
                        {
                            BookId = 5081,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5082,
                            AuthorId = 2005
                        },
                        new
                        {
                            BookId = 5083,
                            AuthorId = 2012
                        },
                        new
                        {
                            BookId = 5084,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5085,
                            AuthorId = 2015
                        },
                        new
                        {
                            BookId = 5086,
                            AuthorId = 2014
                        },
                        new
                        {
                            BookId = 5087,
                            AuthorId = 2008
                        },
                        new
                        {
                            BookId = 5088,
                            AuthorId = 2026
                        },
                        new
                        {
                            BookId = 5089,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5090,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5091,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5092,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5093,
                            AuthorId = 2026
                        },
                        new
                        {
                            BookId = 5094,
                            AuthorId = 2028
                        },
                        new
                        {
                            BookId = 5095,
                            AuthorId = 2027
                        },
                        new
                        {
                            BookId = 5096,
                            AuthorId = 2021
                        },
                        new
                        {
                            BookId = 5097,
                            AuthorId = 2024
                        },
                        new
                        {
                            BookId = 5098,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5099,
                            AuthorId = 2025
                        },
                        new
                        {
                            BookId = 5100,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5101,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5102,
                            AuthorId = 2023
                        },
                        new
                        {
                            BookId = 5103,
                            AuthorId = 2022
                        },
                        new
                        {
                            BookId = 5104,
                            AuthorId = 2027
                        },
                        new
                        {
                            BookId = 5105,
                            AuthorId = 2026
                        });
                });

            modelBuilder.Entity("QLTV.Models.BorrowDetail", b =>
                {
                    b.Property<int>("ReceiptId")
                        .HasColumnType("int");

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("FineAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ReceiptId", "BookId");

                    b.HasIndex("BookId");

                    b.ToTable("BorrowDetails");

                    b.HasData(
                        new
                        {
                            ReceiptId = 6001,
                            BookId = 5001,
                            ActualReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6001,
                            BookId = 5002,
                            ActualReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6002,
                            BookId = 5003,
                            ActualReturnDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6002,
                            BookId = 5004,
                            ActualReturnDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6003,
                            BookId = 5005
                        },
                        new
                        {
                            ReceiptId = 6003,
                            BookId = 5006
                        },
                        new
                        {
                            ReceiptId = 6004,
                            BookId = 5007
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BookId = 5008,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 15000m
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BookId = 5009,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 20000m
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BookId = 5010,
                            ActualReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 2.00m
                        },
                        new
                        {
                            ReceiptId = 6006,
                            BookId = 5011
                        },
                        new
                        {
                            ReceiptId = 6006,
                            BookId = 5012
                        },
                        new
                        {
                            ReceiptId = 6007,
                            BookId = 5013
                        },
                        new
                        {
                            ReceiptId = 6007,
                            BookId = 5014
                        },
                        new
                        {
                            ReceiptId = 6008,
                            BookId = 5015,
                            ActualReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6008,
                            BookId = 5016,
                            ActualReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FineAmount = 0m
                        },
                        new
                        {
                            ReceiptId = 6009,
                            BookId = 5017
                        },
                        new
                        {
                            ReceiptId = 6009,
                            BookId = 5018
                        },
                        new
                        {
                            ReceiptId = 6010,
                            BookId = 5019
                        },
                        new
                        {
                            ReceiptId = 6010,
                            BookId = 5020
                        });
                });

            modelBuilder.Entity("QLTV.Models.BorrowReceipt", b =>
                {
                    b.Property<int>("ReceiptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReceiptId"), 6001L);

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReceiptId");

                    b.HasIndex("UserId");

                    b.ToTable("BorrowReceipts");

                    b.HasData(
                        new
                        {
                            ReceiptId = 6001,
                            BorrowDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1001
                        },
                        new
                        {
                            ReceiptId = 6002,
                            BorrowDate = new DateTime(2025, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1002
                        },
                        new
                        {
                            ReceiptId = 6003,
                            BorrowDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1003
                        },
                        new
                        {
                            ReceiptId = 6004,
                            BorrowDate = new DateTime(2025, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1001
                        },
                        new
                        {
                            ReceiptId = 6005,
                            BorrowDate = new DateTime(2025, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1002
                        },
                        new
                        {
                            ReceiptId = 6006,
                            BorrowDate = new DateTime(2025, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1003
                        },
                        new
                        {
                            ReceiptId = 6007,
                            BorrowDate = new DateTime(2025, 6, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1001
                        },
                        new
                        {
                            ReceiptId = 6008,
                            BorrowDate = new DateTime(2025, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ReturnDate = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Returned",
                            UserId = 1002
                        },
                        new
                        {
                            ReceiptId = 6009,
                            BorrowDate = new DateTime(2025, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1003
                        },
                        new
                        {
                            ReceiptId = 6010,
                            BorrowDate = new DateTime(2025, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Borrowed",
                            UserId = 1001
                        });
                });

            modelBuilder.Entity("QLTV.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"), 3001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 3001,
                            Name = "Văn học Việt Nam"
                        },
                        new
                        {
                            CategoryId = 3002,
                            Name = "Văn học nước ngoài"
                        },
                        new
                        {
                            CategoryId = 3003,
                            Name = "Nghiên cứu khoa học"
                        },
                        new
                        {
                            CategoryId = 3004,
                            Name = "Lịch sử – Địa lý"
                        },
                        new
                        {
                            CategoryId = 3005,
                            Name = "Công nghệ thông tin"
                        },
                        new
                        {
                            CategoryId = 3006,
                            Name = "Tâm lý – Kỹ năng sống"
                        },
                        new
                        {
                            CategoryId = 3007,
                            Name = "Thiếu nhi"
                        },
                        new
                        {
                            CategoryId = 3008,
                            Name = "Kinh tế – Quản trị"
                        },
                        new
                        {
                            CategoryId = 3009,
                            Name = "Y học – Sức khỏe"
                        },
                        new
                        {
                            CategoryId = 3010,
                            Name = "Nghệ thuật – Kiến trúc"
                        },
                        new
                        {
                            CategoryId = 3011,
                            Name = "Truyện tranh – Manga"
                        },
                        new
                        {
                            CategoryId = 3012,
                            Name = "Tự lực – Phát triển bản thân"
                        },
                        new
                        {
                            CategoryId = 3013,
                            Name = "Thơ ca"
                        },
                        new
                        {
                            CategoryId = 3014,
                            Name = "Du lịch – Khám phá"
                        },
                        new
                        {
                            CategoryId = 3015,
                            Name = "Ẩm thực – Nấu ăn"
                        },
                        new
                        {
                            CategoryId = 3016,
                            Name = "Văn học trẻ"
                        },
                        new
                        {
                            CategoryId = 3017,
                            Name = "Tiểu thuyết trinh thám"
                        },
                        new
                        {
                            CategoryId = 3018,
                            Name = "Kinh dị – Giật gân"
                        },
                        new
                        {
                            CategoryId = 3019,
                            Name = "Thơ cách mạng"
                        },
                        new
                        {
                            CategoryId = 3020,
                            Name = "Tôn giáo – Triết học"
                        },
                        new
                        {
                            CategoryId = 3021,
                            Name = "Khoa học viễn tưởng"
                        },
                        new
                        {
                            CategoryId = 3022,
                            Name = "Lãng mạn – Tình cảm"
                        },
                        new
                        {
                            CategoryId = 3023,
                            Name = "Phát triển bản thân"
                        },
                        new
                        {
                            CategoryId = 3024,
                            Name = "Kinh doanh – Khởi nghiệp"
                        },
                        new
                        {
                            CategoryId = 3025,
                            Name = "Sách kỹ năng mềm"
                        },
                        new
                        {
                            CategoryId = 3026,
                            Name = "Văn hóa – Xã hội"
                        },
                        new
                        {
                            CategoryId = 3027,
                            Name = "Sách thiếu nhi – Thiếu niên"
                        },
                        new
                        {
                            CategoryId = 3028,
                            Name = "Sách luật pháp"
                        },
                        new
                        {
                            CategoryId = 3029,
                            Name = "Sách đại học"
                        },
                        new
                        {
                            CategoryId = 3030,
                            Name = "Sách chuyên ngành y"
                        });
                });

            modelBuilder.Entity("QLTV.Models.Publisher", b =>
                {
                    b.Property<int>("PublisherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublisherId"), 4001L);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PublisherId");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            PublisherId = 4001,
                            Name = "NXB Giáo dục Việt Nam"
                        },
                        new
                        {
                            PublisherId = 4002,
                            Name = "NXB Văn hóa – Thông tin"
                        },
                        new
                        {
                            PublisherId = 4003,
                            Name = "NXB Khoa học và Kỹ thuật"
                        },
                        new
                        {
                            PublisherId = 4004,
                            Name = "NXB Trẻ"
                        },
                        new
                        {
                            PublisherId = 4005,
                            Name = "NXB Kim Đồng"
                        },
                        new
                        {
                            PublisherId = 4006,
                            Name = "NXB Thống Kê"
                        },
                        new
                        {
                            PublisherId = 4007,
                            Name = "NXB Đại học Quốc gia"
                        },
                        new
                        {
                            PublisherId = 4008,
                            Name = "NXB Công nghệ Thông tin"
                        },
                        new
                        {
                            PublisherId = 4009,
                            Name = "NXB Hội Nhà văn"
                        },
                        new
                        {
                            PublisherId = 4010,
                            Name = "NXB Văn học"
                        },
                        new
                        {
                            PublisherId = 4011,
                            Name = "NXB Phụ nữ"
                        },
                        new
                        {
                            PublisherId = 4012,
                            Name = "NXB Tri thức"
                        },
                        new
                        {
                            PublisherId = 4013,
                            Name = "NXB Phương Đông"
                        },
                        new
                        {
                            PublisherId = 4014,
                            Name = "NXB Văn học Đông Á"
                        },
                        new
                        {
                            PublisherId = 4015,
                            Name = "NXB Đại học Quốc gia TP.HCM"
                        },
                        new
                        {
                            PublisherId = 4016,
                            Name = "NXB An ninh quốc gia"
                        });
                });

            modelBuilder.Entity("QLTV.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1001L);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1001,
                            Address = "Số 12, ngõ 34 Phố Hoàng Hoa Thám, Quận Ba Đình, Hà Nội",
                            Email = "vanvu@gmail.com",
                            FullName = "Nguyễn Văn Vũ",
                            Password = "P@ssw0rd1",
                            Phone = "0912345678",
                            Username = "nguyenvanvu"
                        },
                        new
                        {
                            UserId = 1002,
                            Address = "Số 45, Đường 3/2, Phường Hưng Lợi, Quận Ninh Kiều, TP. Cần Thơ",
                            Email = "thiba@gmail.com",
                            FullName = "Trần Thị Ba",
                            Password = "B@Password2",
                            Phone = "0987654321",
                            Username = "tranthiba"
                        },
                        new
                        {
                            UserId = 1003,
                            Address = "Số 78, Phố Nguyễn Văn Cừ, Phường Gia Thuỷ, TP. Bắc Ninh",
                            Email = "vanchi@gmail.com",
                            FullName = "Lê Văn Chi",
                            Password = "Ch1Secure!",
                            Phone = "0901234567",
                            Username = "levanchi"
                        });
                });

            modelBuilder.Entity("QLTV.Models.Book", b =>
                {
                    b.HasOne("QLTV.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTV.Models.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("QLTV.Models.BookAuthor", b =>
                {
                    b.HasOne("QLTV.Models.Author", "Author")
                        .WithMany("BookAuthors")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTV.Models.Book", "Book")
                        .WithMany("BookAuthors")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("QLTV.Models.BorrowDetail", b =>
                {
                    b.HasOne("QLTV.Models.Book", "Book")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLTV.Models.BorrowReceipt", "BorrowReceipt")
                        .WithMany("BorrowDetails")
                        .HasForeignKey("ReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("BorrowReceipt");
                });

            modelBuilder.Entity("QLTV.Models.BorrowReceipt", b =>
                {
                    b.HasOne("QLTV.Models.User", "User")
                        .WithMany("BorrowReceipts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLTV.Models.Author", b =>
                {
                    b.Navigation("BookAuthors");
                });

            modelBuilder.Entity("QLTV.Models.Book", b =>
                {
                    b.Navigation("BookAuthors");

                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("QLTV.Models.BorrowReceipt", b =>
                {
                    b.Navigation("BorrowDetails");
                });

            modelBuilder.Entity("QLTV.Models.Category", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLTV.Models.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("QLTV.Models.User", b =>
                {
                    b.Navigation("BorrowReceipts");
                });
#pragma warning restore 612, 618
        }
    }
}
